# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 452b5929a3a9ca74b0e46c530dbd76585a898d98116b876f5a03143802c0ee789c10d290ec35cbd2f2a71abd15c271602e24313b23f9e0421859b28d4ac10e47

test:
  secret_key_base: 85817dc5402d6ec01c5a55712b0e48fb125e5773b658d20e08740b24a52a2dab45464d677404dfcd7b7bb263a382f68ae71bbc25e9804e953e5b401fc2290ab5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
